opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - single_test_class
  - unneeded_parentheses_in_closure_argument
  - private_over_fileprivate
  - sorted_imports

disabled_rules:
  - file_length
  - line_length
  - trailing_comma
  - switch_case_alignment
  - discarded_notification_center_observer
  - identifier_name
  - cyclomatic_complexity
  - type_body_length
  - function_body_length
  - type_name
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - todo
  - nesting
  - syntactic_sugar
  - legacy_hashing

included:
  - ../Source

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - NantesTests
  - build
